"""
Event Types & Priority Taxonomy for JALDRISHTI AI Event-Driven Streaming.
Defines all operational event categories, lifecycle states, and priority classes.
"""

from enum import Enum

class EventPriority(str, Enum):
    CRITICAL = "CRITICAL" # Safety alerts, human review required, critical data outages (NEVER dropped)
    HIGH = "HIGH"         # Forecast completed, inundation updated, impact escalated
    NORMAL = "NORMAL"     # Routine observations, regular state transitions
    LOW = "LOW"           # Diagnostic heartbeats, non-essential telemetry pings

class EventType(str, Enum):
    # Ingestion & Source Health
    SOURCE_CONNECTED = "SOURCE_CONNECTED"
    SOURCE_DISCONNECTED = "SOURCE_DISCONNECTED"
    SOURCE_HEALTH_CHANGED = "SOURCE_HEALTH_CHANGED"
    SOURCE_DATA_RECEIVED = "SOURCE_DATA_RECEIVED"
    SOURCE_DATA_REJECTED = "SOURCE_DATA_REJECTED"
    SOURCE_DATA_BECAME_STALE = "SOURCE_DATA_BECAME_STALE"

    # Domain Observation Updates
    RAIN_OBSERVATION_UPDATED = "RAIN_OBSERVATION_UPDATED"
    RAINFALL_FUSION_UPDATED = "RAINFALL_FUSION_UPDATED"
    NWP_UPDATED = "NWP_UPDATED"
    RIVER_OBSERVATION_UPDATED = "RIVER_OBSERVATION_UPDATED"
    IMD_AWS_OBSERVATION_UPDATED = "IMD_AWS_OBSERVATION_UPDATED"
    IMD_AWS_SOURCE_HEALTH_CHANGED = "IMD_AWS_SOURCE_HEALTH_CHANGED"
    IMD_AWS_INGESTION_FAILED = "IMD_AWS_INGESTION_FAILED"

    # Forecasting Pipeline Lifecycle
    FORECAST_TRIGGERED = "FORECAST_TRIGGERED"
    FORECAST_STARTED = "FORECAST_STARTED"
    FORECAST_COMPLETED = "FORECAST_COMPLETED"
    FORECAST_FAILED = "FORECAST_FAILED"

    # Hydrology, Inundation & Impact
    HYDROLOGY_UPDATED = "HYDROLOGY_UPDATED"
    INUNDATION_STARTED = "INUNDATION_STARTED"
    INUNDATION_UPDATED = "INUNDATION_UPDATED"
    IMPACT_UPDATED = "IMPACT_UPDATED"

    # Alert State Machine
    ALERT_CANDIDATE_CREATED = "ALERT_CANDIDATE_CREATED"
    ALERT_STATE_CHANGED = "ALERT_STATE_CHANGED"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    ALERT_ACKNOWLEDGED = "ALERT_ACKNOWLEDGED"

    # Phase 13-16 Specialized Event Streams
    ANOMALY_DETECTED = "ANOMALY_DETECTED"
    OBSERVATION_VALIDATED = "OBSERVATION_VALIDATED"
    RISK_STATE_CHANGED = "RISK_STATE_CHANGED"
    RISK_EXPLANATION_UPDATED = "RISK_EXPLANATION_UPDATED"
    INUNDATION_CHANGE_DETECTED = "INUNDATION_CHANGE_DETECTED"
    IMPACT_CHANGE_DETECTED = "IMPACT_CHANGE_DETECTED"
    ALERT_DECISION_EXECUTED = "ALERT_DECISION_EXECUTED"

    # System & Map State
    MODE_CHANGED = "MODE_CHANGED"
    MAP_STATE_CHANGED = "MAP_STATE_CHANGED"
