"""
Deterministic 14-Stage Master Demo Scenario (DEMO-MAHANADI-STORM-01).
Provides mathematically coherent, physically bounded hydrometeorological trajectories
driving genuine end-to-end causal behavior across the JALDRISHTI AI platform.
"""

from typing import List, Dict, Any, Optional
from dataclasses import dataclass
from services.models import AlertSeverity, ConfidenceLevel

@dataclass
class DemoScenarioStage:
    index: int
    stage_id: str
    name: str
    headline: str
    description: str
    rainfall_rate_mm_hr: float
    rainfall_acc_6h_mm: float
    river_stage_m: float
    river_discharge_cumec: float
    inundated_area_sqkm: float
    exposed_population: int
    exposed_villages: int
    risk_score: float
    previous_risk_score: float
    material_risk_delta: float
    top_causal_driver: str
    alert_severity: AlertSeverity
    requires_operator_review: bool
    is_notification_dispatched: bool
    data_confidence: ConfidenceLevel

DEMO_SCENARIO_STAGES: List[DemoScenarioStage] = [
    DemoScenarioStage(
        index=0,
        stage_id="T0_NORMAL",
        name="NORMAL",
        headline="Baseline Dry-Weather Conditions",
        description="Normal seasonal baseline. River stages well below warning thresholds. Minimal isolated drizzle.",
        rainfall_rate_mm_hr=2.0,
        rainfall_acc_6h_mm=8.5,
        river_stage_m=21.20,
        river_discharge_cumec=4200.0,
        inundated_area_sqkm=0.0,
        exposed_population=0,
        exposed_villages=0,
        risk_score=14.2,
        previous_risk_score=14.2,
        material_risk_delta=0.0,
        top_causal_driver="Stable baseline hydrometeorological indicators",
        alert_severity=AlertSeverity.GREEN,
        requires_operator_review=False,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=1,
        stage_id="T1_RAINFALL_ONSET",
        name="RAINFALL_ONSET",
        headline="Convective Cell Development",
        description="Radar and satellite fusion detects rapid convective cloud clustering over Upper Mahanadi catchment.",
        rainfall_rate_mm_hr=12.5,
        rainfall_acc_6h_mm=28.0,
        river_stage_m=21.80,
        river_discharge_cumec=5600.0,
        inundated_area_sqkm=0.0,
        exposed_population=0,
        exposed_villages=0,
        risk_score=22.0,
        previous_risk_score=14.2,
        material_risk_delta=7.8,
        top_causal_driver="+5.2 pts from 6h rainfall onset; +2.6 pts from atmospheric CAPE spike",
        alert_severity=AlertSeverity.GREEN,
        requires_operator_review=False,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=2,
        stage_id="T2_HEAVY_RAIN",
        name="HEAVY_RAIN",
        headline="Intense Precipitation Nowcast Surge",
        description="ConvLSTM nowcaster predicts intense storm band (>35 mm/h) across Cuttack and Kendrapara districts.",
        rainfall_rate_mm_hr=38.5,
        rainfall_acc_6h_mm=74.0,
        river_stage_m=22.60,
        river_discharge_cumec=8400.0,
        inundated_area_sqkm=4.2,
        exposed_population=1200,
        exposed_villages=2,
        risk_score=36.5,
        previous_risk_score=22.0,
        material_risk_delta=14.5,
        top_causal_driver="+10.8 pts from heavy rainfall accumulation; +3.7 pts from local surface runoff",
        alert_severity=AlertSeverity.YELLOW,
        requires_operator_review=False,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=3,
        stage_id="T3_RUNOFF_INCREASE",
        name="RUNOFF_INCREASE",
        headline="Catchment Soil Saturation & Runoff Surge",
        description="Catchment soil moisture reaches 88%. Rapid overland runoff routes into tributary channels.",
        rainfall_rate_mm_hr=48.0,
        rainfall_acc_6h_mm=126.0,
        river_stage_m=23.45,
        river_discharge_cumec=12500.0,
        inundated_area_sqkm=18.5,
        exposed_population=5400,
        exposed_villages=6,
        risk_score=48.2,
        previous_risk_score=36.5,
        material_risk_delta=11.7,
        top_causal_driver="+7.4 pts from saturated basin runoff; +4.3 pts from river inflow acceleration",
        alert_severity=AlertSeverity.YELLOW,
        requires_operator_review=False,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=4,
        stage_id="T4_RIVER_RISING",
        name="RIVER_RISING",
        headline="Rapid Stage Inflow at Mundali & Naraj",
        description="Upstream barrage release surges to 16,800 cumecs. Water level rises at +0.25 m/hr.",
        rainfall_rate_mm_hr=42.0,
        rainfall_acc_6h_mm=168.0,
        river_stage_m=24.60,
        river_discharge_cumec=16800.0,
        inundated_area_sqkm=42.0,
        exposed_population=12800,
        exposed_villages=14,
        risk_score=59.0,
        previous_risk_score=48.2,
        material_risk_delta=10.8,
        top_causal_driver="+6.8 pts from upstream hydro surge; +4.0 pts from floodplain water accumulation",
        alert_severity=AlertSeverity.ORANGE,
        requires_operator_review=False,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=5,
        stage_id="T5_THRESHOLD_APPROACH",
        name="THRESHOLD_APPROACH",
        headline="River Stage Crossing Warning Level (25.40m)",
        description="Mundali stage crosses Warning Mark (25.40m). Hydraulic model triggers critical embankment monitoring.",
        rainfall_rate_mm_hr=32.0,
        rainfall_acc_6h_mm=195.0,
        river_stage_m=25.55,
        river_discharge_cumec=19200.0,
        inundated_area_sqkm=78.4,
        exposed_population=24500,
        exposed_villages=22,
        risk_score=68.5,
        previous_risk_score=59.0,
        material_risk_delta=9.5,
        top_causal_driver="+6.1 pts from warning level breach; +3.4 pts from expanded vulnerability buffer",
        alert_severity=AlertSeverity.ORANGE,
        requires_operator_review=False,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=6,
        stage_id="T6_FLOOD_PROBABILITY_HIGH",
        name="FLOOD_PROBABILITY_HIGH",
        headline="Hydraulic Breach Probability Exceeds 85%",
        description="2D hydrodynamic surrogate projects extensive overtopping along Kathajodi distributary within 4 hours.",
        rainfall_rate_mm_hr=26.0,
        rainfall_acc_6h_mm=212.0,
        river_stage_m=26.15,
        river_discharge_cumec=21800.0,
        inundated_area_sqkm=112.0,
        exposed_population=36000,
        exposed_villages=29,
        risk_score=76.2,
        previous_risk_score=68.5,
        material_risk_delta=7.7,
        top_causal_driver="+4.9 pts from hydrodynamic overtopping hazard; +2.8 pts from population exposure",
        alert_severity=AlertSeverity.ORANGE,
        requires_operator_review=True,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=7,
        stage_id="T7_INUNDATION_EXPANSION",
        name="INUNDATION_EXPANSION",
        headline="Major Floodplain Inundation (158 km²)",
        description="Overtopping inundates Cuttack and Jagatsinghpur lowlands. Inundation depth reaches 0.8m - 1.6m.",
        rainfall_rate_mm_hr=18.5,
        rainfall_acc_6h_mm=225.0,
        river_stage_m=26.50,
        river_discharge_cumec=23500.0,
        inundated_area_sqkm=158.2,
        exposed_population=48000,
        exposed_villages=38,
        risk_score=83.4,
        previous_risk_score=76.2,
        material_risk_delta=7.2,
        top_causal_driver="+4.5 pts from inundation footprint expansion; +2.7 pts from critical road blockages",
        alert_severity=AlertSeverity.RED,
        requires_operator_review=True,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=8,
        stage_id="T8_EXPOSURE_SURGE",
        name="EXPOSURE_SURGE",
        headline="Critical Asset & Infrastructure Impact",
        description="Major highway NH-16 culvert submerged. 3 primary health centers and 12 schools inside alert zone.",
        rainfall_rate_mm_hr=14.0,
        rainfall_acc_6h_mm=232.0,
        river_stage_m=26.70,
        river_discharge_cumec=24800.0,
        inundated_area_sqkm=192.0,
        exposed_population=58200,
        exposed_villages=45,
        risk_score=89.0,
        previous_risk_score=83.4,
        material_risk_delta=5.6,
        top_causal_driver="+3.4 pts from critical facility exposure; +2.2 pts from high flow velocity (>1.2 m/s)",
        alert_severity=AlertSeverity.RED,
        requires_operator_review=True,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=9,
        stage_id="T9_RISK_SPIKE",
        name="RISK_SPIKE",
        headline="River Peak Cresting Near HFL (26.85m)",
        description="Peak flood wave reaches 26.85m (+0.55m above Danger Mark). Maximum floodplain storage reached.",
        rainfall_rate_mm_hr=8.0,
        rainfall_acc_6h_mm=238.0,
        river_stage_m=26.85,
        river_discharge_cumec=25600.0,
        inundated_area_sqkm=215.4,
        exposed_population=64500,
        exposed_villages=52,
        risk_score=94.5,
        previous_risk_score=89.0,
        material_risk_delta=5.5,
        top_causal_driver="+3.8 pts from peak hydro crest; +1.7 pts from compounded duration",
        alert_severity=AlertSeverity.RED,
        requires_operator_review=True,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=10,
        stage_id="T10_ALERT_CANDIDATE",
        name="ALERT_CANDIDATE",
        headline="RED Emergency Evacuation Alert Generated",
        description="Automated Early Warning Engine generates RED Evacuation Alert. Operator review gate engaged.",
        rainfall_rate_mm_hr=4.5,
        rainfall_acc_6h_mm=240.0,
        river_stage_m=26.80,
        river_discharge_cumec=25200.0,
        inundated_area_sqkm=214.0,
        exposed_population=64500,
        exposed_villages=52,
        risk_score=93.8,
        previous_risk_score=94.5,
        material_risk_delta=-0.7,
        top_causal_driver="Emergency alert criteria sustained across all delta distributary nodes",
        alert_severity=AlertSeverity.RED,
        requires_operator_review=True,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=11,
        stage_id="T11_OPERATOR_APPROVAL",
        name="OPERATOR_APPROVAL",
        headline="Operator Review & Authorization Gate Passed",
        description="EOC Commander verifies data confidence (HIGH) and authorizes multi-channel citizen alert broadcast.",
        rainfall_rate_mm_hr=2.0,
        rainfall_acc_6h_mm=240.5,
        river_stage_m=26.65,
        river_discharge_cumec=24100.0,
        inundated_area_sqkm=208.0,
        exposed_population=63000,
        exposed_villages=50,
        risk_score=90.2,
        previous_risk_score=93.8,
        material_risk_delta=-3.6,
        top_causal_driver="Authorized emergency response protocol initiated",
        alert_severity=AlertSeverity.RED,
        requires_operator_review=False,
        is_notification_dispatched=True,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=12,
        stage_id="T12_PUBLIC_NOTIFICATION",
        name="PUBLIC_NOTIFICATION",
        headline="Geofenced Public Citizen Alert Dispatched",
        description="Mock SMS, FCM Push, and In-App warnings delivered to DEMO USER in Cuttack. OUTSIDE USER excluded.",
        rainfall_rate_mm_hr=0.8,
        rainfall_acc_6h_mm=241.0,
        river_stage_m=26.30,
        river_discharge_cumec=22000.0,
        inundated_area_sqkm=195.0,
        exposed_population=59000,
        exposed_villages=48,
        risk_score=82.0,
        previous_risk_score=90.2,
        material_risk_delta=-8.2,
        top_causal_driver="Citizen alerts acknowledged; localized evacuation routing underway",
        alert_severity=AlertSeverity.ORANGE,
        requires_operator_review=False,
        is_notification_dispatched=True,
        data_confidence=ConfidenceLevel.HIGH
    ),
    DemoScenarioStage(
        index=13,
        stage_id="T13_RECOVERY",
        name="RECOVERY",
        headline="Flood Waters Receding into Bay of Bengal",
        description="Rainfall ceases completely. Inundated floodplain drains through tidal outfalls. Risk level demoting.",
        rainfall_rate_mm_hr=0.0,
        rainfall_acc_6h_mm=241.0,
        river_stage_m=24.80,
        river_discharge_cumec=15500.0,
        inundated_area_sqkm=84.0,
        exposed_population=18000,
        exposed_villages=16,
        risk_score=45.0,
        previous_risk_score=82.0,
        material_risk_delta=-37.0,
        top_causal_driver="-37.0 pts from receding floodwaters and river stage recovery below danger level",
        alert_severity=AlertSeverity.YELLOW,
        requires_operator_review=False,
        is_notification_dispatched=False,
        data_confidence=ConfidenceLevel.HIGH
    )
]
